### ISSUE TITLE
Add weather.coffee

### ISSUE THREAD

**Issue by camiller** [danehammer/mwdc_parrotbot#1]
Would you consider adding https://github.com/github/hubot-scripts/blob/master/src/scripts/weather.coffee to parrotbot?

**Comment by danehammer** [comment]
Sure, would you like to take a stab at it? I would check if there's an npm package that provides it, otherwise turn it on by updating config file (since it's from hubot-scripts).

**Comment by camiller** [comment]
I'll give it a go, but with my wife sick and other family things going on it might be on the back burner till next week.
